### ISSUE TITLE
Wrong Curriculum Start Date Displayed for Berlin

### ISSUE THREAD

**Issue by markmonta** [AdeoRessi/FI#56]
Ben and I tried to fix it ourselves, but did not. The starting date under "Curriculum Calendar" says "2015-03-25"

See snapshot: 

![screen shot 2015-03-11 at 2 51 01 pm](https://cloud.githubusercontent.com/assets/6173881/6607722/397f603a-c7fe-11e4-82a7-062594d7e1ea.png)

**Comment by AdeoRessi** [comment]
Click “+” next to Orientation and Graduation on the Admin/Courses page (http://FI.co/admin/courses). This will save the start and end dates…
