### ISSUE TITLE
Mentor Cannot Upload Mentor Agreement

### ISSUE THREAD

**Issue by markmonta** [AdeoRessi/FI#60]
Signed in as: m.roggendorf@blackchili.de 
Code: uwXSbV
Browser: Chrome

There is no option to upload the agreement when it usually says "On File" or "Browse".

![screen shot 2015-03-24 at 6 08 53 pm](https://cloud.githubusercontent.com/assets/6173881/6816481/19a35f0c-d251-11e4-8437-abc2cd0b6cac.png)

**Comment by AdeoRessi** [comment]
Mark, has he actually been confirmed for a session? - Adeo
